console.log('/////////////SWAPPING-VARIABLIES///////////');
var sweety='Sweety';
var cutie="Cutie";
console.log('**********BEFORE-SWAPPING**********');
console.log('Value of sweety:',sweety,', Value of cutie:', cutie);
var temp=sweety;
sweety=cutie;
cutie=temp;
console.log('**********AFTER-SWAPPING**********');
console.log('Value of sweety:',sweety,', Value of cutie:', cutie);
var num1=100;
var num2=200;
var num3=300;
console.log('**********BEFORE-SWAPPING**********');
console.log('Value of num1 is',num1,'Value of num2 is',num2, 'Value of num2 is ',num3);
var temp1=num1;
num1=num2;
num2=num3;
num3=temp1;
console.log('**********AFTER-SWAPPING**********');
console.log('Value of num1 is',num1,'Value of num2 is',num2, 'Value of num2 is ',num3);
